##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    # use_usd_kinematics: False
    usd_path: "/usd/flatten_updated_1.usd"
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "robot/ur_description/ur3e_lab.urdf"
    asset_root_path: "robot/ur_description"
    
    base_link: "base_link"
    ee_link: "gripper_center"
    link_names: null
    lock_joints: null
    extra_links: null

    
    collision_link_names: ['shoulder_link','upper_arm_link', 'forearm_link', 'wrist_1_link', 'wrist_2_link' ,'wrist_3_link','single_base'] # List[str]
    collision_spheres:
      shoulder_link:
        - "center": [-0.0, 0.0, -0.02]
          "radius": 0.055
        - "center": [0.01, -0.019, -0.0]
          "radius": 0.045
        - "center": [0.004, -0.007, 0.019]
          "radius": 0.05
      upper_arm_link:
        - "center": [-0.008, 0.0, 0.127]
          "radius": 0.056
        - "center": [-0.091, 0.0, 0.127]
          "radius": 0.054
        - "center": [-0.174, -0.0, 0.13]
          "radius": 0.051
        - "center": [-0.242, -0.0, 0.106]
          "radius": 0.048
        - "center": [-0.15, 0.0, 0.105]
          "radius": 0.051
        - "center": [0.0, 0.0, 0.11]
          "radius": 0.056
        - "center": [-0.245, 0.005, 0.143]
          "radius": 0.043
        - "center": [-0.058, -0.002, 0.105]
          "radius": 0.052
        - "center": [-0.055, 0.001, 0.132]
          "radius": 0.055
        - "center": [-0.14, 0.0, 0.133]
          "radius": 0.052
      forearm_link:
        - "center": [-0.084, -0.0, 0.033]
          "radius": 0.044
        - "center": [-0.157, -0.0, 0.035]
          "radius": 0.043
        - "center": [-0.008, -0.0, 0.053]
          "radius": 0.043
        - "center": [-0.213, 0.0, 0.074]
          "radius": 0.042
        - "center": [-0.213, -0.0, 0.021]
          "radius": 0.042
        - "center": [-0.13, -0.0, 0.022]
          "radius": 0.044
        - "center": [-0.003, -0.003, 0.041]
          "radius": 0.037
        - "center": [-0.118, 0.001, 0.039]
          "radius": 0.044
        - "center": [-0.059, -0.001, 0.037]
          "radius": 0.044
        - "center": [-0.168, -0.0, 0.016]
          "radius": 0.043
      wrist_1_link:
        - "center": [0.0, -0.009, -0.002]
          "radius": 0.041
        - "center": [-0.003, 0.019, 0.001]
          "radius": 0.037
        - "center": [0.006, 0.007, -0.024]
          "radius": 0.033
      wrist_2_link:
        - "center": [-0.0, 0.0, -0.015]
          "radius": 0.041
        - "center": [-0.0, 0.012, 0.001]
          "radius": 0.039
        - "center": [-0.0, -0.018, -0.001]
          "radius": 0.04
      wrist_3_link:
        - "center": [0.0, 0.002, -0.025]
          "radius": 0.035
      single_base:
        - "center": [-0.00206, -0.000247, 0.02466]
          "radius": 0.042
        - "center": [0.00554, -0.05164, -0.01031]
          "radius": 0.02
        - "center": [0.03286, -0.04086, -0.01015]
          "radius": 0.02
        # - "center": [0.01, -0.019, -0.0]
        #   "radius": 0.045
        # - "center": [0.004, -0.007, 0.019]
        #   "radius": 0.05
    
    collision_sphere_buffer: 0.005
    extra_collision_spheres: {}
    self_collision_ignore: {
      "upper_arm_link": ["forearm_link", "shoulder_link"],
      "forearm_link": ["wrist_1_link", "wrist_2_link", "wrist_3_link"],
      "wrist_1_link": ["wrist_2_link","wrist_3_link"],
      "wrist_2_link": ["wrist_3_link"],
      "single_base": ["wrist_3_link","wrist_2_link"],
      }
    self_collision_buffer: {'upper_arm_link': 0, 
      'forearm_link': 0, 
      'wrist_1_link': 0, 
      'wrist_2_link': 0,
      'wrist_3_link' : 0,
      'single_base' : 0,
      } 
      
    # use_global_cumul: True
    mesh_link_names: null # List[str]

    cspace:
      joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
      retract_config:  [-2.105, -3.615, 2.429, -1.096, 1.939, -0.406]
      null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 15.0
